### ISSUE TITLE
Ecmascript 6

### ISSUE THREAD

**Issue by evgenTraytyak** [AdamBrodzinski/validate-form#14]
@AdamBrodzinski @patrickml  what you think about using es6 syntax(`ecmascript` package)?

**Comment by patrickml** [comment]
@evgenTraytyak tho Ecmascript 6 is pretty BA im not sure if it would make a large difference on this package since this is all front end code and no major browsers support es6 yet the es6 code will just be compiled into es5

Thanks for trying to stay ahead of the game tho!

**Comment by evgenTraytyak** [comment]
@patrickml I think you're right. `es6` for this package won't make large difference.

**Comment by AdamBrodzinski** [comment]
@evgenTraytyak I love ES6 but anyone who would use this would automatically incur the file size of the polyfills. I think plain old ES5 is best for libraries.
