### ISSUE TITLE
Failure to validate long-domain emails

### ISSUE THREAD

**Issue by iancwinter** [AdamBrodzinski/validate-form#20]
Using the "email" validator, finding it is currently failing with long email domains. My specific example: foo@bar.productions

**Comment by AdamBrodzinski** [comment]
Thanks for the bug report @iancwinter !

It looks like this line is suspect...

https://github.com/AdamBrodzinski/validate-form/blob/master/validators/email.js#L4

I think changing 4 to 255 would be correct (max of 255 chars)

```
var isValid =  !! email.trim().match(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,255}$/ig);
```

Could you send a PR and i'll merge it in 👍

**Comment by iancwinter** [comment]
Apologies, I missed this response last year, and now the same bug has manifested itself as one of our users’ emails is something@domainname.photos.

I believe your suggestion is correct – either use `{2,255}` or just `{2,}` would allow any length above 1.

**Comment by AdamBrodzinski** [comment]
closing as your PR fixes this. I just bumped the version and am working on publishing that to Atmosphere. Thanks again! 🍻
