### ISSUE TITLE
blur and focus events do not set

### ISSUE THREAD

**Issue by tyler-dunkel** [AdamBrodzinski/validate-form#5]
Hi Adam,
I think I have found a reason why the root layout config is not working for me. Any chances this it? I notice you use focus and blur in the events in client.js. 
http://info.meteor.com/blog/browser-events-bubbling-capturing-and-delegation

**Comment by AdamBrodzinski** [comment]
Hmm it's possible. Do you have multiple layouts setup? It works great for me with one layout. One flaw in the current version is that it assumes you only have one. I'll be changing this soon as i'll need to do this in an upcoming project next week. The new version will depreciate the root layout config and will just use jQuery to bubble all events up the the body.

Cheers!

**Comment by patrickml** [comment]
@AdamBrodzinski wow its funny that you had thought of the same thing lol just so you know i created a PR that will fix this

**Comment by AdamBrodzinski** [comment]
Thanks! just pulled it in :+1:

**Comment by AdamBrodzinski** [comment]
btw, if you're interested in being a contributor let me know. I've made new 'functional' approach to this that uses underscore chaining so I prob. won't be updating this much.

**Comment by patrickml** [comment]
@AdamBrodzinski i am interested. I have an idea of how the package can have extensions for additional validators

**Comment by AdamBrodzinski** [comment]
Cool, added!  Also just published to Atmosphere. One validator that would be nice is a regex that could be used inline with the input.... not sure if Blaze can do that yet? (i've been using a lot of React lately) Something like:

``` javascript
<form class='validate'>
  <input type="text" data-onblur data-regex={/[\w]-foo$/} />
</form>

```

Feel free to add more validators or cleanup/ etc... :beers:  (if there's breaking changes we can bump a major version too)

**Comment by patrickml** [comment]
For sure I think the way im going to set it up is so the validator is the core and then you can add validator-regex, validator-email, validator-something that way you only have the code loaded for what you need
